CREATE TABLE IF NOT EXISTS settings (
    `key`      VARCHAR(255) NOT NULL PRIMARY KEY,
    value      TEXT         NOT NULL,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
